apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue

data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb/catalogue"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # these lables are deployment lables
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: 1
  selector:
  # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
# This is pod definition. pod is subset of replica set
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: vinod1618/catalogue:1.6.0
        imagePullPolicy: Always  # this is safe to pull evrytime, there may be images with same version rebuilt and pushes
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "150Mi"
        #readiness probe

        readinessProbe:
          httpGet:
              path: /health
              port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        #liveness probe

        livenessProbe:
          tcpSocket:
              port: 8080
          failureThreshold: 2
          periodSeconds: 10

        envFrom:
        - configMapRef:
            name: catalogue

---

apiVersion: v1
kind: Service
metadata: 
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  selector:
  #lables are used as selectors
    project: roboshop
    tier: backend
    component: catalogue
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20